cd [file dirname [info script]]
add_files [glob *.sv]
add_files [glob *.svh]
add_files [glob bpb/*.sv]
add_files [glob mult/*.sv]
add_files [glob mult/*.svh]
add_files [glob mult/*/*.xci]
add_files [glob top/*.sv]