name: svlint

on: [push, pull_request]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test using svlint
      uses: dalance/svlint-action@master
      with:
        files: |
          5-stage-pipeline-plain/code/*
